server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://zhuyuqinlan.io:3306/lemall?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  data:
    redis:
      host: zhuyuqinlan.io
      port: 6379
      password: 123456
    mongodb:
      uri: mongodb://root:123456@zhuyuqinlan.io:27017/lemall-portal?authSource=admin&authMechanism=SCRAM-SHA-1
minio:
  endpoint: http://zhuyuqinlan.io:9000 #MinIO服务所在地址(局域网)
  publicEndpoint: http://zhuyuqinlan.io:9000 # 前端直传和回显时使用(公网)开发环境都用局域网
  accessKey: wud5C5TvSdXzVTUk51Mh #访问的key
  secretKey: dvkNmUKGYRBBKXFXKR7RJHLCbz1v81kp0O0ciEkF #访问的秘钥
localFile:
  base-path: D:/upload/lemall # 文件上传目录
  local-download-prefix: /file-dev/local-download # 开发环境使用本地上传，文件访问url的前缀
  access-url-prefix: "http://localhost:8080${localFile.local-download-prefix}" # 网络访问
secure:
  ignore:
    urls: #配置白名单路径
      - "/doc.html"
      - "/v3/api-docs/**"
      - "/webjars/**"
      - "/favicon.ico"
      - "${localFile.local-download-prefix}/**"
      - "${lemall.server.prefix.common}/captcha/email/getAuthCode"
      - "${lemall.server.prefix.admin}/system/admin/login"
      - "${lemall.server.prefix.portal}/sso/login"
      - "${lemall.server.prefix.portal}/sso/register"
logging:
  level:
    root: DEBUG
