server:
  port: 8080
# 开启或启用knife4j生产模式
knife4j:
  production: false
spring:
  datasource:
    url: jdbc:mysql://lemall-mysql:3306/lemall?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  data:
    redis:
      host: lemall-redis
      port: 6379
      password: 123456
    mongodb:
      uri: mongodb://root:123456@lemall-mongodb:27017/lemall-portal?authSource=admin&authMechanism=SCRAM-SHA-1
minio:
  endpoint: http://lemall-minio:9000 #MinIO服务所在地址(内网)
  publicEndpoint: http://zhuyuqinlan.io:9000 # 前端直传和回显时使用(公网)
  accessKey: wud5C5TvSdXzVTUk51Mh #访问的key
  secretKey: dvkNmUKGYRBBKXFXKR7RJHLCbz1v81kp0O0ciEkF #访问的秘钥
localFile:
  base-path: /usr/local/upload/lemall # 文件上传目录
  access-url-prefix: http://zhuyuqinlan.io/lemall-nginx/file-prod/local-download # 网络访问前缀（这里用nginx反代访问和nginx约定访问路径，如果nginx和后端不在同一台服务器，那要让后端将文件上传到共享目录中）
secure:
  ignore:
    urls: #配置白名单路径
      - "/doc.html"
      - "/v3/api-docs/**"
      - "/webjars/**"
      - "/favicon.ico"
      - "${lemall.server.prefix.common}/captcha/email/getAuthCode"
      - "${lemall.server.prefix.admin}/system/admin/login"
      - "${lemall.server.prefix.portal}/sso/login"
      - "${lemall.server.prefix.portal}/sso/register"
