server:
  port: 8080
# 开启knife4j生产模式
knife4j:
  production: true
spring:
  datasource:
    url: jdbc:mysql://lemall-mysql:3306/lemall?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  data:
    redis:
      host: lemall-redis
      port: 6379
      password: 123456
    mongodb:
      uri: mongodb://root:123456@lemall-mogodb:27017/lemall-portal?authSource=admin&authMechanism=SCRAM-SHA-1
minio:
  endpoint: http://lemall-minio:9000 #MinIO服务所在地址(内网)
  publicEndpoint: https://zhuyuqinlan.org:9000 # 前端直传和回显时使用(公网)
  accessKey: wud5C5TvSdXzVTUk51Mh #访问的key
  secretKey: dvkNmUKGYRBBKXFXKR7RJHLCbz1v81kp0O0ciEkF #访问的秘钥
