server:
  port: 8080
# 开启knife4j生产模式
knife4j:
  production: true
spring:
  datasource:
    url: jdbc:mysql://lemall-mysql:3306/lemall?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  data:
    redis:
      host: lemall-redis
      port: 6379
      password: 123456
    mongodb:
      uri: mongodb://root:123456@lemall-mogodb:27017/lemall-portal?authSource=admin&authMechanism=SCRAM-SHA-1
minio:
  endpoint: http://lemall-minio:9000 #MinIO服务所在地址
  accessKey: 8pox7jXJXi98WC5n2f1H #访问的key
  secretKey: a5J1qPkZfgua0N1UdyVNuIv1wk8okgbK5U8URkvM #访问的秘钥
