server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://zhuyuqinlan.io:3306/lemall?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  data:
    redis:
      host: zhuyuqinlan.io
      port: 6379
      password: 123456
    mongodb:
      uri: mongodb://root:123456@zhuyuqinlan.io:27017/lemall-portal?authSource=admin&authMechanism=SCRAM-SHA-1
minio:
  endpoint: http://zhuyuqinlan.io:9000 #MinIO服务所在地址(局域网)
  publicEndpoint: http://zhuyuqinlan.io:9000 # 前端直传和回显时使用(公网)开发环境都用局域网
  accessKey: wud5C5TvSdXzVTUk51Mh #访问的key
  secretKey: dvkNmUKGYRBBKXFXKR7RJHLCbz1v81kp0O0ciEkF #访问的秘钥
