server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://nanguo.io:3306/lemall?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  data:
    redis:
      host: nanguo.io
      port: 6379
      password: 123456
minio:
  endpoint: http://nanguo.io:9000 #MinIO服务所在地址
  accessKey: 8pox7jXJXi98WC5n2f1H #访问的key
  secretKey: a5J1qPkZfgua0N1UdyVNuIv1wk8okgbK5U8URkvM #访问的秘钥