spring:
  application:
    name: lemall
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB # 单个文件最大
      max-request-size: 50MB # 总文件最大
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid: # Druid 连接池
      initial-size: 5 # 初始化连接池大小
      min-idle: 5 # 最小连接池数量
      max-active: 20 # 最大连接池数量
      max-wait: 60000 # 连接时最大等待时间（单位：毫秒）
      test-while-idle: true
      time-between-eviction-runs-millis: 60000 # 配置多久进行一次检测，检测需要关闭的连接（单位：毫秒）
      min-evictable-idle-time-millis: 300000 # 配置一个连接在连接池中最小生存的时间（单位：毫秒）
      max-evictable-idle-time-millis: 900000 # 配置一个连接在连接池中最大生存的时间（单位：毫秒）
      validation-query: SELECT 1 FROM DUAL # 配置测试连接是否可用的查询 sql
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/* # 配置监控后台访问路径
        login-username: admin # 配置监控后台登录的用户名、密码
        login-password: admin
      filter:
        stat:
          enabled: true
          log-slow-sql: true # 开启慢 sql 记录
          slow-sql-millis: 2000 # 若执行耗时大于 2s，则视为慢 sql
          merge-sql: true
        wall: # 防火墙
          config:
            multi-statement-allow: true
  data:
    redis:
      database: 1 # 设置redis使用的数据库编号
redis:
  common-prefix: lemall
  key:
    expire:
      common: 7776000    # 默认过期时间（秒）
    auth:
      pathResourceMap: auth:pathResourceMap    # 资源列表，固定 key
      captcha:
        code: auth:captcha:code:{type}:{target}      # 验证码key
        limit: auth:captcha:limit:{type}:{target}   # 验证码次数限制
    fs:
      access:
        localFileAccess: fs:access:local:{token}   # 本地上传 access code
      url:
        cacheByFileId: fs:url:fileId:{fileId}   # 文件ID -> URL
        lockByFileId: fs:url:lock:fileId:{fileId} # 防击穿
      info:
        cacheByMd5: fs:info:md5:{md5}       # MD5 -> 文件信息
        lockByMd5: fs:info:lock:md5:{md5}      #  防击穿
############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: Authorization
  # token有效期，单位秒，-1代表永不过期
  timeout: 7776000
  # token临时有效期 (指定时间内无操作就视为token过期)，单位秒
  active-timeout: -1
  # 是否允许同一账号并发登录 (为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false
  # 是否从cookie中读取token
  is-read-cookie: false
  # 是否从head中读取token
  is-read-header: true
  # token前缀
  token-prefix: Bearer
  # jwt秘钥
  jwt-secret-key: zhuyuqinzuinb66f
  # 是否打印banner
  is-print: false
minio:
  bucketName: lemall #存储桶名称
springdoc:
  info:
    title: Lemall后台系统
    description: lemall商城项目后端接口文档
    version: v0.0.1
    summary: 基于springboot
    terms-of-service: https://zhuyuqinlan.org
    contact:
      name: zhuyuqinlan
      url: https://zhuyuqinlan.org
      email: echonanguo@qq.com
    license:
      name: Apache 2.0
      url: https://www.apache.org/licenses/LICENSE-2.0.html
    securitySchemeName: ${sa-token.token-name}

knife4j:
  enable: true
  setting:
    language: zh-CN
    swagger-model-name: 实体类列表
    enable-host-text: localhost:8080
lemall:
  server:
    prefix:
      common: /api/lemall-common
      admin: /api/lemall-admin
      portal: /api/lemall-portal
mybatis-plus:
  mapper-locations:
    - classpath*:mapper/**/*.xml
    - classpath*:dao/**/*.xml
