server:
  port: 8080
# 开启或启用knife4j生产模式
knife4j:
  production: false
spring:
  datasource:
    url: jdbc:mysql://lemall-mysql:3306/lemall?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  data:
    redis:
      host: lemall-redis
      port: 6379
      password: 123456
    mongodb:
      uri: mongodb://root:123456@lemall-mongodb:27017/lemall-portal?authSource=admin&authMechanism=SCRAM-SHA-1
logging:
  level:
    root: INFO
