services:
  redis:
    image: redis:5.0.14
    container_name: lemall-redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
    command: redis-server --requirepass ${REDIS_PASSWD}
    environment:
      - TZ=Asia/Shanghai

  mysql:
    image: mysql:8.0
    container_name: lemall-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWD}
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d

  minio:
    container_name: lemall-minio
    image: minio/minio:RELEASE.2025-03-12T18-04-18Z-cpuv1
    command: server --console-address ":9001" /data
    environment:
      - MINIO_ROOT_USER=${MINIO_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_PASSWD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio/data:/data
      
  elasticsearch:
    container_name: lemall-elasticsearch
    image: elasticsearch:8.10.4
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    #      - "9300:9300"
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/plugins:/usr/share/elasticsearch/plugins
      - ./elasticsearch/logs:/usr/share/elasticsearch/logs

  kibana:
    container_name: lemall-kibana
    image: kibana:8.10.4
    environment:
      - I18N_LOCALE=zh-CN
      - TZ=Asia/Shanghai
      - ELASTICSEARCH_HOSTS=http://lemall-elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch  

  mongodb:
    image: mongo:5.0.9
    container_name: lemall-mongodb
    ports:
      - 27017:27017
    volumes:
      - ./mongodb-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWD}

