server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://zhuyuqinlan.io:3306/lemall?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  data:
    redis:
      host: zhuyuqinlan.io
      port: 6379
      password: 123456
    mongodb:
      uri: mongodb://root:123456@zhuyuqinlan.io:27017/lemall-portal?authSource=admin&authMechanism=SCRAM-SHA-1
logging:
  level:
    root: DEBUG
